vich_uploader:
    db_driver: orm

    mappings:
      post_image:
        uri_prefix: /images/posts/albums
        upload_destination: '%kernel.project_dir%/public/images/posts/albums'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
      images:
        uri_prefix: /images/posts
        upload_destination: '%kernel.project_dir%/public/images/posts'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
      images_category:
        uri_prefix: /images/categories
        upload_destination: '%kernel.project_dir%/public/images/categories'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
      avatars:
        uri_prefix: /images/avatars
        upload_destination: '%kernel.project_dir%/public/images/avatars'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
      pays:
        uri_prefix: /images/pays
        upload_destination: '%kernel.project_dir%/public/images/pays'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
      videos:
        uri_prefix: /videos/posts
        upload_destination: '%kernel.project_dir%/public/videos/posts'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true

